#region AuthorHeader
//
//	Jail version 2.0, by Xanthos
//
//  Based on original code and concept by Sirens Song
//  (ie, Matron de Winter) 2004 and Grim Reaper.  Thanks to
//	Thundar for his ideas and testing.
//
#endregion AuthorHeader
using System;
using System.IO;
using System.Text;
using Server;
using Server.Items;
using Server.Mobiles;
using Server.Targeting;
using System.Collections;
using Xanthos.Utilities;

namespace Xanthos.JailSystem
{
	// This file is for configuration of the Jail System.  It is advised
	// that you DO NOT edit this file, instead place JailConfig.xml in the 
	// RunUO/Data directory and modify the values there to configure the system
	// without changing code.  This allows you to take updates to the system
	// without losing your specific configuration settings.

	public class JailConfig
	{
		// Configurable options
		public static AccessLevel JailImmuneLevel = AccessLevel.Administrator;
		public static bool JailWordsEnabled = false;
		public static int UsesRemaining = 100;
		public static int FineAmount = 10000;
		public static string RobeTitle = "Property Of Xanthos Jail";
		public static int RobeHue = 2083;
		public static int RockHue = 2597;
		public static string WhatToMine = "rock"; 
		public static int HammerDifficulty = 65; 
		public static Point3D JailLocation = new Point3D( 1715, 1064, 0 );
		public static Point3D FreeLocation = new Point3D( 3770, 1308, 0 );
		public static Point3D FreeMurdererLocation = new Point3D( 3770, 1308, 0 );
		public static Map JailMap = Map.Trammel;
		public static Map FreeMap = Map.Trammel;
		public static Map FreeMurdererMap = Map.Felucca;
		public static string JailRockName = "Jail Rock";
		public static double JailRockWeight = 3.0;
		public static string JailWordFile = "Data/jailwords.txt";


		private const string kConfigFile = @"Data/JailConfig.xml";
		private const string kConfigName = "JailSystem";

		public static void Initialize()
		{
			Element element = ConfigParser.GetConfig( kConfigFile, kConfigName );

			if ( null == element || element.ChildElements.Count <= 0 )
				return;

			AccessLevel tempAccessLevel;
			bool tempBool;
			int tempInt;
			double tempDouble;
			Point3D tempPoint3D;
			Map tempMap;

			foreach( Element child in element.ChildElements) 
			{
				if ( child.TagName == "JailImmuneLevel" && child.GetAccessLevelValue( out tempAccessLevel ))
					JailImmuneLevel = tempAccessLevel;
				
				else if ( child.TagName == "JailWordsEnabled" && child.GetBoolValue( out tempBool ))
					JailWordsEnabled = tempBool;

				else if ( child.TagName == "UsesRemaining" && child.GetIntValue( out tempInt ))
					UsesRemaining = tempInt;

				else if ( child.TagName == "FineAmount" && child.GetIntValue( out tempInt ))
					FineAmount = tempInt;

				else if ( child.TagName == "RobeTitle" && null != child.Text )
					RobeTitle = child.Text;

				else if ( child.TagName == "RobeHue" && child.GetIntValue( out tempInt ))
					RobeHue = tempInt;

				else if ( child.TagName == "RockHue" && child.GetIntValue( out tempInt ))
					RockHue = tempInt;

				else if ( child.TagName == "WhatToMine" && null != child.Text )
					WhatToMine = child.Text;

				else if ( child.TagName == "HammerDifficulty" && child.GetIntValue( out tempInt ))
					HammerDifficulty = tempInt;

				else if ( child.TagName == "JailLocation" && child.GetPoint3DValue( out tempPoint3D ))
					JailLocation = tempPoint3D;

				else if ( child.TagName == "JailMap" && child.GetMapValue( out tempMap ))
					JailMap = tempMap;

				else if ( child.TagName == "FreeLocation" && child.GetPoint3DValue( out tempPoint3D ))
					FreeLocation = tempPoint3D;

				else if ( child.TagName == "FreeMap" && child.GetMapValue( out tempMap ))
					FreeMap = tempMap;
			
				else if ( child.TagName == "FreeMurdererLocation" && child.GetPoint3DValue( out tempPoint3D ))
					FreeMurdererLocation = tempPoint3D;

				else if ( child.TagName == "FreeMurdererMap" && child.GetMapValue( out tempMap ))
					FreeMurdererMap = tempMap;

				else if ( child.TagName == "JailRockName" && null != child.Text )
					JailRockName = child.Text;

				else if ( child.TagName == "JailWordFile" && null != child.Text )
					JailWordFile = child.Text;

				else if ( child.TagName == "JailRockWeight" && child.GetDoubleValue( out tempDouble ))
					JailRockWeight = tempDouble;
			}
		}

	}
}