/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya,              //
// modified for coloring by Manu               //
// Splitterwelt.com                            //
// german roleplay freeshard                   //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;

namespace Server.Items
{
	public class LightMarbleRunebeetleStatueAddon : BaseAddon
	{
		public override BaseAddonDeed Deed{ get{ return new LightMarbleRunebeetleStatueAddonDeed(); } }

		public override bool RetainDeedHue{ get{ return true; } }

		[Constructable]
		public LightMarbleRunebeetleStatueAddon() : this( 0 )
		{
		}

		[ Constructable ]
		public LightMarbleRunebeetleStatueAddon( int hue )
		{
			AddonComponent ac;
			ac = new AddonComponent( 10095 );
			ac.Hue = hue;
			ac.Name = "Marble Runebeetle Statue";
			AddComponent( ac, 0, 0, 11 );
			ac = new AddonComponent( 4643 );
			ac.Hue = 1150;
			ac.Name = "Marble Statue Pedestal";
			AddComponent( ac, 0, 0, 0 );
		}

		public LightMarbleRunebeetleStatueAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );

			writer.Write( (int) 1 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );

			int version = reader.ReadInt();
		}
	}

	public class LightMarbleRunebeetleStatueAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon { get{ return new LightMarbleRunebeetleStatueAddon( this.Hue ); } }

		[Constructable]
		public LightMarbleRunebeetleStatueAddonDeed()
		{
			Name = "Marble Runebeetle Statue (Bright Socket)";
		}

		public LightMarbleRunebeetleStatueAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}