/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class NecroAltarAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new NecroAltarAddonDeed();
			}
		}

		[ Constructable ]
		public NecroAltarAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 4622 );
			ac.Hue = 1109;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 4623 );
			ac.Hue = 1109;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 4624 );
			ac.Hue = 1109;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 4625 );
			ac.Hue = 1109;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 4626 );
			ac.Hue = 1109;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 4627 );
			ac.Hue = 1109;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 4628 );
			ac.Hue = 1109;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 4629 );
			ac.Hue = 1109;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 4630 );
			ac.Hue = 1109;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6571 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 0, 0, 4 );
			ac = new AddonComponent( 6881 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 6882 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6938 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6935 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 6939 );
			AddComponent( ac, 0, -1, 0 );

		}

		public NecroAltarAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class NecroAltarAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new NecroAltarAddon();
			}
		}

		[Constructable]
		public NecroAltarAddonDeed()
		{
			Name = "necro altar";
		}

		public NecroAltarAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}