/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya,              //
// modified for coloring by Manu               //
// Splitterwelt.com                            //
// german roleplay freeshard                   //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;

namespace Server.Items
{
	public class DarkMarbleGargoyleStatueAddon : BaseAddon
	{
		public override BaseAddonDeed Deed{ get{ return new DarkMarbleGargoyleStatueAddonDeed(); } }

		public override bool RetainDeedHue{ get{ return true; } }

		[Constructable]
		public DarkMarbleGargoyleStatueAddon() : this( 0 )
		{
		}

		[ Constructable ]
		public DarkMarbleGargoyleStatueAddon( int hue )
		{
			AddonComponent ac;
			ac = new AddonComponent( 9613 );
			ac.Hue = hue;
			ac.Name = "Marble Gargoyle Statue";
			AddComponent( ac, 0, 0, 13 );
			ac = new AddonComponent( 4643 );
			ac.Hue = 2406;
			ac.Name = "Marble Statue Pedestal";
			AddComponent( ac, 0, 0, 0 );
		}

		public DarkMarbleGargoyleStatueAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );

			writer.Write( (int) 1 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );

			int version = reader.ReadInt();
		}
	}

	public class DarkMarbleGargoyleStatueAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon { get{ return new DarkMarbleGargoyleStatueAddon( this.Hue ); } }

		[Constructable]
		public DarkMarbleGargoyleStatueAddonDeed()
		{
			Name = "Marble Gargoyle Statue (Dark Pedestal)";
		}

		public DarkMarbleGargoyleStatueAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}